name: bayesaxs
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=0.13.0
  - alsa-lib=1.2.3
  - arviz=0.11.2
  - astunparse=1.6.3
  - backcall=0.2.0
  - binutils=2.35.1
  - binutils_impl_linux-64=2.35.1
  - binutils_linux-64=2.35
  - blosc=1.21.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - c-compiler=1.2.0
  - ca-certificates=2021.7.5
  - cachetools=4.2.2
  - certifi=2021.5.30
  - cftime=1.5.0
  - curl=7.77.0
  - cxx-compiler=1.2.0
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=5.0.9
  - dill=0.3.4
  - expat=2.4.1
  - fastprogress=1.0.0
  - filelock=3.0.12
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gcc_impl_linux-64=9.3.0
  - gcc_linux-64=9.3.0
  - gettext=0.19.8.1
  - glib=2.68.3
  - glib-tools=2.68.3
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.4
  - gxx_impl_linux-64=9.3.0
  - gxx_linux-64=9.3.0
  - hdbscan=0.8.27
  - hdf4=4.2.15
  - hdf5=1.10.6
  - icu=68.1
  - intel-openmp=2021.3.0
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - jax=0.2.17
  - jaxlib=0.1.67
  - jbig=2.1
  - jedi=0.17.0
  - joblib=1.0.1
  - jpeg=9d
  - kernel-headers_linux-64=2.6.32
  - kiwisolver=1.3.1
  - krb5=1.19.1
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.77.0
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=11.1.0
  - libgfortran5=11.1.0
  - libglib=2.68.3
  - libgomp=9.3.0
  - libgpuarray=0.7.6
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnetcdf=4.8.0
  - libnghttp2=1.43.0
  - libogg=1.3.4
  - libopenblas=0.3.15
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.3
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzip=1.8.0
  - lz4-c=1.9.3
  - lzo=2.10
  - mako=1.1.4
  - markupsafe=2.0.1
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - mdtraj=1.9.6
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mock=4.0.3
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - ncurses=6.2
  - netcdf4=1.5.7
  - nspr=4.30
  - nss=3.67
  - numexpr=2.7.3
  - numpy=1.21.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - opt_einsum=3.3.0
  - packaging=21.0
  - pandas=1.3.0
  - parso=0.8.2
  - patsy=0.5.1
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.1.3
  - prompt-toolkit=3.0.17
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pygments=2.9.0
  - pygpu=0.7.6
  - pymc3=3.11.2
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pytables=3.6.1
  - python=3.8.10
  - python-dateutil=2.8.2
  - python-flatbuffers=2.0
  - python_abi=3.8
  - pytz=2021.1
  - qt=5.12.9
  - readline=8.1
  - scikit-learn=0.24.2
  - scipy=1.7.0
  - semver=2.13.0
  - setuptools=52.0.0
  - six=1.16.0
  - snappy=1.1.8
  - sqlite=3.36.0
  - sysroot_linux-64=2.12
  - theano=1.0.5
  - theano-pymc=1.1.2
  - threadpoolctl=2.2.0
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - typing-extensions=3.10.0.0
  - typing_extensions=3.10.0.0
  - wcwidth=0.2.5
  - wheel=0.36.2
  - xarray=0.18.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
